rm ./new_powersoftau.ptau &>/dev/null
rm ./verification_key.json &>/dev/null
rm ./witness.json &>/dev/null
rm ./witness.wtns &>/dev/null
rm ./Verifier.sol &>/dev/null
rm ./public.json &>/dev/null
rm ./proof.json &>/dev/null
rm ./input.json &>/dev/null
rm ./circuit.json &>/dev/null
rm ./circuit.circom &>/dev/null
rm ./circuit.r1cs &>/dev/null
rm ./circuit.sym &>/dev/null
rm ./circuit.wasm &>/dev/null
rm ./circuit.zkey &>/dev/null
rm ./calldata.json &>/dev/null
rm ./proving_key.json &>/dev/null
rm ./vk.bin &>/dev/null
rm ./pk.bin &>/dev/null
rm ./proof.bin &>/dev/null
rm ./srs2^20.key &>/dev/null
